# -*- coding: utf-8 -*-
"""lab_03_A3_44(Part 2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19k1c1qso9CS9kxZu4b8cldDaxsze_tub
"""

##  Lab- 03 (Part 2)
## MultiClass Logistic Regression

import pandas as pd
from sklearn.model_selection import train_test_split

data=pd.read_csv('Iris.csv')
data

data['Species'].unique()

data['Species'].replace({'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3})
data

data

x_train,x_test,y_train,y_test=train_test_split(data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']],data['Species'],train_size=0.2)

x_train

y_train

from sklearn import linear_model
mymodel=linear_model.LogisticRegression()
mymodel.fit(x_train,y_train)

mymodel.predict(x_test)

x_test

mymodel.score(x_test,y_test)

predicted_output=mymodel.predict(x_test)
predicted_output

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,predicted_output)
cm

import seaborn as sn
from matplotlib import pyplot as plt
sn.heatmap(cm,annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')

