# -*- coding: utf-8 -*-
"""Lab_03_A3_44(Part 3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15N1JDvIgOjSSv5YmpIwufpaPamb4V0om
"""

## lab - 03 (Part 3)
## Underfitting and overfitting in data

import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('Age.csv')
data

plt.xlabel('Age')
plt.ylabel('Employed(Y/N)')
plt.scatter(data['Age'],data['Employed'],marker='*')

from sklearn import linear_model
linmodel = linear_model.LinearRegression()
linmodel.fit(data[['Age']],data.Employed)

plt.xlabel('Age')
plt.ylabel('Employed')
plt.scatter(data.Age, data.Employed)
plt.plot(data.Age, linmodel.predict(data[['Age']]), color='green')

from sklearn import linear_model
logmodel = linear_model.LogisticRegression()
logmodel.fit(data[['Age']],data.Employed)

plt.xlabel('Age')
plt.ylabel('Employed')
plt.scatter(data.Age, data.Employed)
plt.plot(data.Age, logmodel.predict(data[['Age']]), color='green')

linmodel.score(data[['Age']],data.Employed)

logmodel.score(data[['Age']],data.Employed)

